add fonts and a few mixins
orrymevorach/nora-camps pull request #2
Opened 2023-03-22 05:49 UTC by orrymevorach

2023-03-22 22:39 UTC, andyb2 requested changes

2023-03-22 22:39 UTC, andyb2 commented on src/components/shared/nav/nav.module.scss
@import is being phased out. @use would be the new way to connect files.

The Sass team discourages the continued use of the @import rule. Sass will [gradually phase it out](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline) over the next few years, and eventually remove it from the language entirely. Prefer the [@use rule](https://sass-lang.com/documentation/at-rules/use) instead. (Note that only Dart Sass currently supports @use. Users of other implementations must use the @import rule instead.)

What’s Wrong With @import?
The @import rule has a number of serious issues:

@import makes all variables, mixins, and functions globally accessible. This makes it very difficult for people (or tools) to tell where anything is defined.

Because everything’s global, libraries must add a prefix to all their members to avoid naming collisions.

[@extend rules](https://sass-lang.com/documentation/at-rules/extend) are also global, which makes it difficult to predict which style rules will be extended.

Each stylesheet is executed and its CSS emitted every time it’s @imported, which increases compilation time and produces bloated output.

There was no way to define private members or placeholder selectors that were inaccessible to downstream stylesheets.

The new module system and the @use rule address all these problems.

2023-03-22 22:39 UTC, andyb2 commented on src/components/shared/nav/nav.jsx
Looks to be a potential conflict due to the main branch containing the new nav bar. Might need to merge from main.

2023-03-23 16:48 UTC, orrymevorach commented on src/components/shared/nav/nav.module.scss
Ah interesting! Will make the change

2023-03-23 20:56 UTC, andyb2 approved these changes

2023-03-23 20:58 UTC, merged